#PBS -N mbc_d.6_.0.15
#PBS -l nodes=1:ppn=4
#PBS -j oe
#PBS -S /bin/bash
#PBS -l walltime=99:00:00

#tdate=$(date +%%T)

set -x
cd /nfs/01/osu6683/
source .bash_profile

cd /nfs/01/osu6683/biclique_workflow/MergeNetPackage/MAFIA-MBC
time /nfs/01/osu6683/biclique_workflow/MergeNetPackage/MAFIA-MBC/bin/MBC fci /nfs/01/osu6683/test/gse15745_gpl6104_gpl8490_dcor_adj_6.dat 15.00 /nfs/01/osu6683/test/gse15745_gpl6104_gpl8490_dcor_adj_6.15.biclique 0